#!/usr/bin/env bash
# Generate esp32c6-wifi.ld: TinyGo's targets/esp32c6.ld extended with the
# ESP32-C6 mask-ROM symbols the WiFi blobs need.
#
# On the C6, large parts of pp/net80211/phy/coexist live in the mask ROM
# (unlike the C3, where the .a archives are self-contained).  Linking the
# blobs therefore requires the ROM symbol addresses from ESP-IDF's
# components/esp_rom/esp32c6/ld/.  This script:
#
#   1. takes TinyGo's stock targets/esp32c6.ld (dev branch),
#   2. shrinks SRAM from 512K to 0x7E610 so TinyGo's heap/GC stays below
#      SOC_ROM_STACK_START (0x4087e610): the top 6.5K of HP SRAM holds the
#      ROM stack plus the ROM PHY/pp/net80211/coexist data region
#      (phy_param_rom = 0x4087fce8 ... coex_env_ptr = 0x4087ffc4),
#   3. adds the blob IRAM input sections (.wifi*iram*, .iram1*, .coexiram*,
#      .phyiram*) to .iram — without .coexiram* the libcoexist sections
#      become orphan image blocks at unaligned addresses and the boot ROM
#      rejects the image ("Invalid image block"),
#   4. appends the ROM symbol files: rom, api, phy, net80211, pp and
#      coexist PROVIDE-wrapped (object files win on conflict); libgcc plain;
#      memset/memcpy/memmove from newlib plain (forces the ROM versions).
#
# Usage: tools/gen_esp32c6_ld.sh [idf-ld-dir] > esp32c6-wifi.ld
#   idf-ld-dir: directory containing esp32c6.rom*.ld from ESP-IDF v5.3.1
#               (downloaded from GitHub if not given).

set -euo pipefail

IDF_TAG=v5.3.1
TINYGO_REF=dev
RAW_IDF="https://raw.githubusercontent.com/espressif/esp-idf/$IDF_TAG/components/esp_rom/esp32c6/ld"
RAW_TINYGO="https://raw.githubusercontent.com/tinygo-org/tinygo/$TINYGO_REF/targets/esp32c6.ld"

workdir=$(mktemp -d)
trap 'rm -rf "$workdir"' EXIT

lddir=${1:-}
if [ -z "$lddir" ]; then
    lddir=$workdir
    for f in esp32c6.rom.ld esp32c6.rom.api.ld esp32c6.rom.phy.ld \
             esp32c6.rom.net80211.ld esp32c6.rom.pp.ld esp32c6.rom.coexist.ld \
             esp32c6.rom.libgcc.ld esp32c6.rom.newlib.ld; do
        curl -sSf -o "$lddir/$f" "$RAW_IDF/$f" >&2
    done
fi

curl -sSf -o "$workdir/base.ld" "$RAW_TINYGO" >&2

# Wrap plain `sym = 0xADDR;` assignments in PROVIDE(); leave comments,
# existing PROVIDE()s and alias assignments untouched.  Lines that IDF
# disabled with a leading `//` are converted to /* */ comments: `//` is NOT
# a comment in linker-script syntax, and lld would otherwise define literal
# symbols named e.g. `//wDev_ProcessFiq`.
wrap_provide() {
    sed -E \
        -e 's|^//(.*)$|/* \1 */|' \
        -e 's/^([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*=[[:space:]]*(0x[0-9a-fA-F]+)[[:space:]]*;/PROVIDE( \1 = \2 );/' \
        "$1"
}

# 1+2+3: patch the stock script.
#
# The .sbss/.sdata/.srodata edits are load-bearing: the stock script only
# captures *(.sbss) and *(.sdata), but GCC-built archives (the WiFi blobs)
# and clang cgo objects emit RISC-V small-data sections named .sbss.<sym>,
# .sdata.<sym> and .srodata[.cst*|.<sym>].  Unmatched sections are ORPHANS
# placed by lld version-dependent heuristics — with some lld versions they
# land in the flash-mapped IROM/DROM region, where writes are silently
# dropped: variables like the blob's wifi_funcs pointer then "cannot be
# written", which presents as impossible-looking memory corruption that
# moves around between builds.
sed -E \
    -e 's/^(    SRAM \(rwx\) : ORIGIN = 0x40800000, LENGTH = )512K(.*)$/\10x7E610 \/* 512K minus ROM stack + ROM WiFi data (SOC_ROM_STACK_START = 0x4087e610) *\/\2/' \
    -e 's/^([[:space:]]*)\*\(\.sbss\)$/\1*(.sbss .sbss.* .sbss2 .sbss2.* .gnu.linkonce.sb.*) \/* incl. -fdata-sections small BSS *\//' \
    -e 's/^([[:space:]]*)\*\(\.sdata\)$/\1*(.sdata .sdata.* .sdata2 .sdata2.* .gnu.linkonce.s.*) \/* incl. -fdata-sections small data *\//' \
    -e 's/^([[:space:]]*)\*\(\.rodata\*\)$/\1*(.rodata* .srodata .srodata.*) \/* incl. RISC-V small read-only data *\//' \
    -e 's/^([[:space:]]*)\*\(\.iram\*\)([[:space:]]*)(\/\*.*\*\/)?$/\1*(.iram*)     \/* code that must run from IRAM *\/\n\1*(.iram1*)    \/* blob IRAM_ATTR code *\/\n\1*(.wifi*iram*) \/* libpp\/libnet80211 IRAM + sleep\/rx paths *\/\n\1*(.coexiram*) \/* libcoexist IRAM (orphans break the boot image) *\/\n\1*(.phyiram*)  \/* libphy IRAM *\//' \
    "$workdir/base.ld"

cat <<'EOF'

/* ====================================================================
 * ESP32-C6 mask-ROM symbols for the WiFi/BT blobs.
 * Generated by tools/gen_esp32c6_ld.sh from ESP-IDF v5.3.1
 * components/esp_rom/esp32c6/ld/.  Do not edit by hand.
 * ==================================================================== */
EOF

for f in esp32c6.rom.ld esp32c6.rom.api.ld esp32c6.rom.phy.ld \
         esp32c6.rom.net80211.ld esp32c6.rom.pp.ld esp32c6.rom.coexist.ld; do
    echo ""
    echo "/* ---- $f (PROVIDE-wrapped) ---- */"
    wrap_provide "$lddir/$f"
done

echo ""
echo "/* ---- esp32c6.rom.libgcc.ld (plain: ROM versions win) ---- */"
cat "$lddir/esp32c6.rom.libgcc.ld"

echo ""
echo "/* ---- esp32c6.rom.newlib.ld subset (plain: ROM versions win) ---- */"
grep -E '^(memset|memcpy|memmove)[[:space:]]*=' "$lddir/esp32c6.rom.newlib.ld"
